export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ADD_MOVIE = 'ADD_MOVIE';
export const FETCH_MOVIES = 'FETCH_MOVIES';

export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const DECREMENT_ASYNC = 'DECREMENT_ASYNC';

const IMAGES = {
  LOAD: 'IMAGES_LOAD',
  LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
  LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

const STATS = {
  LOAD: 'STATS_LOAD',
  LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
  LOAD_FAIL: 'STATS_LOAD_FAIL',
};

export {IMAGES, STATS};
